package configs

const TOPICS_ORDER_USER_ISSUE = "TOPICS_ORDER_USER_ISSUE"             //用户发起订单
const TOPICS_ORDER_RECYCLER_CONFIRM = "TOPICS_ORDER_RECYCLER_CONFIRM" //回收员确认订单

var TaskTopicsList = []string{TOPICS_ORDER_USER_ISSUE, TOPICS_ORDER_RECYCLER_CONFIRM}
